[package]
name = "google_auth"
version = "0.1.0"
authors = ["Maciej Flak <maciej.jan.flak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-authenticator = "0.1.5"